---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ark-server-charts.yaml
  - backube-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - botkube-charts.yaml
  - factorio-charts.yaml
  - gate-charts.yaml
  - grafana-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - nextcloud-charts.yaml
  - node-feature-discovery.yaml
  - oauth2-server-charts.yaml
  - piraeus-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - vmware-tanzu-charts.yaml
