---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
      lokiAddress: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              label_structured_data: true
              labels:
                job: "syslog"
            relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: host
    extraPorts:
      syslog:
        name: syslog
        containerPort: 1514
        service:
          type: LoadBalancer
          loadBalancerIP: ${SVC_PROMTAIL_ADDRESS}
    serviceMonitor:
      enabled: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: promtail-syslog
            patch:
              - op: remove
                path: /spec/loadBalancerIP
              - op: add
                path: /spec/externalIPs
                value:
                  - ${SVC_PROMTAIL_ADDRESS}
