---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-mariadb
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 14.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: photoprism-mariadb
    image:
      repository: bitnami/mariadb
      tag: 11.1.2
    auth:
      database: photoprism
      username: photoprism
      password: ${SECRET_PHOTOPRISM_MARIADB_PW}
      rootPassword: ${SECRET_PHOTOPRISM_MARIADB_ROOT_PW}
    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: data
      persistence:
        enabled: true
        storageClass: ceph-ssd-xfs
      livenessProbe:
        enabled: true
        initialDelaySeconds: 900
      readinessProbe:
        enabled: false
        initialDelaySeconds: 900
    volumePermissions:
      enabled: true
      image:
        repository: bitnami/bitnami-shell
        tag: 11
    metrics:
      enabled: false
      image:
        repository: bitnami/mysqld-exporter
        tag: 0.15.0
