---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sidero-metallb
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/management/apps/metallb/base
  prune: false
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-management
      - kind: ConfigMap
        name: cluster-settings-management
  decryption:
    provider: sops
    secretRef:
      name: sops-age
