---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  releaseName: ingress-nginx
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
      replicaCount: 3
      config:
        custom-http-errors: 404,401,403,500,503
        hsts-max-age: '31449600'
      use-forwarded-headers: 'true'
      service:
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
        prometheusRule:
          enabled: false
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
