---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: brigman
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes: config
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: homeassistant/home-assistant
              tag: 2023.11.1@sha256:de25f0ad773b54d1c0e5a63147e23417055f3056b0ef24cf4a5ac8019bb33df3
            env:
              TZ: "America/New_York"
            resources:
              limits:
                memory: 2500Mi
                hugepages-2Mi: 500Mi
                cpu: 2000m
              requests:
                cpu: 500m
                memory: 2000Mi
                hugepages-2Mi: 500Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.18.0@sha256:29267847d68332a28d249bd5235715402b144a3903b921da0a1962173aef10b1
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New_York"
            workingDir: /config
            args:
              - --auth
              - none
              - --user-data-dir
              - /config/.vscode
              - --extensions-dir
              - /config/.vscode
              - --port
              - "12321"
            volumeMounts:
              - name: config
                mountPath: /config
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 12321
            protocol: TCP
            targetPort: 12321
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: 'true'
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: "brigman-gate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - secretName: brigman-gate-cert
            hosts:
              - "brigman-gate.${SECRET_DOMAIN}"
      codeserver:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: 'true'
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: ${SECRET_AUTH_URL}
        hosts:
          - host: "brigman-hass-code.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: codeserver
                  port: http
        tls:
          - secretName: brigman-gate-code-cert
            hosts:
              - "brigman-hass-code.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: ceph-ssd-xfs
        retain: true
