---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    master-node: "true"
  name: 4c4c4544-0046-4a10-804d-b7c04f484c32
spec:
  accepted: true
  bmc:
    endpoint: 10.0.15.14
    pass: ${SECRET_CATBERT_IPMI_PASSWORD}
    user: sidero
  configPatches:
  - op: replace
    path: /machine/install/disk
    value: /dev/sdc
  - op: add
    path: /machine/network
    value:
      hostname: catbert
      interfaces:
      - deviceSelector:
          hardwareAddr: e4:1d:2d:22:b8:d0
        dhcp: true
        vip:
          ip: 10.0.14.5
  - op: replace
    path: /machine/certSANs
    value:
    - 10.0.14.5
  - op: add
    path: /cluster/allowSchedulingOnControlPlanes
    value: true
  - op: add
    path: /machine/sysctls
    value:
      vm.nr_hugepages: 1024
  hardware:
    compute:
      processors:
      - manufacturer: Intel
        productName: Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz
    system:
      family: Unknown
      manufacturer: Dell Inc.
      productName: PowerEdge R330
      serialNumber: SKU=NotProvided;ModelName=PowerEdge R330
      skuNumber: Unknown
      version: 7FJMHL2
  hostname: catbert
  pxeBootAlways: true
