---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    worker-node: "true"
  name: 4c4c4544-0031-3810-8047-b4c04f433432
spec:
  accepted: true
  bmc:
    endpoint: 10.0.15.17
    pass: ${SECRET_PHIL_IPMI_PASSWORD}
    user: sidero
  configPatches:
  - op: replace
    path: /machine/install/disk
    value: /dev/sdb
  - op: add
    path: /machine/network
    value:
      interfaces:
      - deviceSelector:
          hardwareAddr: e4:1d:2d:7f:9f:e0
        dhcp: true
  - op: add
    path: /machine/sysctls
    value:
      vm.nr_hugepages: 1024
  hardware:
    compute:
      processors:
      - manufacturer: Intel
        productName: Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz
    system:
      family: Unknown
      manufacturer: Dell Inc.
      productName: PowerEdge R530
      serialNumber: SKU=NotProvided;ModelName=PowerEdge R530
      skuNumber: Unknown
      version: 418GC42
  hostname: phil
  pxeBootAlways: true
