---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  releaseName: sonarr
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 60m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      pullPolicy: IfNotPresent
      tag: v3.0.9.1549
    initContainers:
      update-volume-permission:
        command:
          - sh
          - -c
          - chown -R 568:568 /config
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: config
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: 'true'
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: ${SECRET_AUTH_URL}
          cert-manager.io/cluster-issuer: letsencrypt-production

        hosts:
          - host: sonarr.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: sonarr-cert
            hosts:
              - sonarr.${SECRET_DOMAIN}
    env:
      TZ: America/New_York
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: ceph-hdd
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
      incoming:
        type: pvc
        enabled: true
        existingClaim: incoming-sabnzbd
        mountPath: /incoming
      media:
        type: pvc
        enabled: true
        existingClaim: tv
        mountPath: /media
    podAnnotations:
      backup.velero.io/backup-volumes: config
    metrics:
      enabled: false
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.6.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
