---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.13.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  values:
    installCRDs: false
    webhook:
      enabled: true
    cainjector:
      replicaCount: 1
    podDnsPolicy: ClusterFirst
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
