---
name: lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-cluster-manifests:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1
      - name: Lint Cluster API Manifests
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./clusters
          config_file: ./.github/.yamllint-config
      - name: Lint Manifests
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./manifests
          config_file: ./.github/.yamllint-config
